### PR TITLE
Try two times to clear the reset alert bit

### PR DESCRIPTION
**Pull request by jepler**
.. this is needed at least on CircuitPython 8.0.0-beta.6 and esp32-s3 (prototype esp32-s3 reverse tft feather)

With this change >3000 successive initializations succeeded. Before this change, it did not seem that initialization ever succeeded.

A delay alone was not sufficient to fix the problem.

Since this has only been seen on the esp32-s3, it's likely that this is really one of those core I2C bugs that we love chasing so much. But the workaround is simple and shouldn't hurt anything besides taking a few more bytes of CIRCUITPY.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Yes, let's do it! I will test the older version of the library with the ESP-IDF patch I need to take a look at.

**Comment by dhalbert** [comment]
```
ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/inspect.py)
```
Something may have changed out from under us?? I tried a re-run; didn't help.

**Comment by jepler** [comment]
3.11 "Removed from the [inspect](https://docs.python.org/3.11/library/inspect.html#module-inspect) module:

 *    The getargspec() function, deprecated since Python 3.0; use [inspect.signature()](https://docs.python.org/3.11/library/inspect.html#inspect.signature) or [inspect.getfullargspec()](https://docs.python.org/3.11/library/inspect.html#inspect.getfullargspec) instead.

I'll figure out what's up and fix it.

**Comment by jepler** [comment]
.. but the second failure was different, it was a 'real' pylint failure. I corrected that, let's see how the next run goes.

**Comment by jepler** [comment]
and the other half of the failure is because I branched from an older spot, I think.

**Pull request merged**
